from typing import Protocol


class Repository[T, ID](Protocol):
    def select(self, identifier: ID) -> T: ...
    def insert(self, entity: T) -> None: ...
    def update(self, entity: T) -> None: ...
    def delete(self, identifier: ID) -> None: ...
